"""empty message

Revision ID: 315b78c3128f
Revises: e87a15b79004
Create Date: 2016-03-25 21:14:25.063109

"""

# revision identifiers, used by Alembic.
revision = '315b78c3128f'
down_revision = 'e87a15b79004'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('user', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'wishes', 'user_info', ['user'], ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.drop_column('wishes', 'user')
    ### end Alembic commands ###
