"""empty message

Revision ID: 407c2b84207f
Revises: dfc4ab5380da
Create Date: 2016-03-27 22:22:43.770284

"""

# revision identifiers, used by Alembic.
revision = '407c2b84207f'
down_revision = 'dfc4ab5380da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
