"""empty message

Revision ID: 5386b361b40a
Revises: 6c81a04a9f38
Create Date: 2016-03-21 19:40:39.169097

"""

# revision identifiers, used by Alembic.
revision = '5386b361b40a'
down_revision = '6c81a04a9f38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
