"""empty message

Revision ID: 878765dc1dbc
Revises: 5386b361b40a
Create Date: 2016-03-21 22:00:50.549208

"""

# revision identifiers, used by Alembic.
revision = '878765dc1dbc'
down_revision = '5386b361b40a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
