"""empty message

Revision ID: 9f6768f70e7d
Revises: 505e532843c3
Create Date: 2016-03-18 23:18:28.567750

"""

# revision identifiers, used by Alembic.
revision = '9f6768f70e7d'
down_revision = '505e532843c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('email', sa.String(length=40), nullable=True))
    op.add_column('user_info', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('user_info', 'lname')
    op.drop_column('user_info', 'fname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('fname', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('user_info', sa.Column('lname', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('user_info', 'password')
    op.drop_column('user_info', 'email')
    ### end Alembic commands ###
