"""empty message

Revision ID: ba67c1462262
Revises: 407c2b84207f
Create Date: 2016-03-27 22:26:55.541172

"""

# revision identifiers, used by Alembic.
revision = 'ba67c1462262'
down_revision = '407c2b84207f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
