"""empty message

Revision ID: cf60ec4a3396
Revises: 127ff5f3e92c
Create Date: 2016-04-02 04:28:40.877671

"""

# revision identifiers, used by Alembic.
revision = 'cf60ec4a3396'
down_revision = '127ff5f3e92c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
