"""empty message

Revision ID: e87a15b79004
Revises: 878765dc1dbc
Create Date: 2016-03-25 20:09:49.400803

"""

# revision identifiers, used by Alembic.
revision = 'e87a15b79004'
down_revision = '878765dc1dbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishes')
    ### end Alembic commands ###
